// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-4fT4NOV6tfsVgirRxu2vD1ywAyAU9A',
    appId: '1:653860201928:web:ad960757bf151b9c3f0cfd',
    messagingSenderId: '653860201928',
    projectId: 'pmg-engineering-pvt-ltd',
    authDomain: 'pmg-engineering-pvt-ltd.firebaseapp.com',
    storageBucket: 'pmg-engineering-pvt-ltd.firebasestorage.app',
    measurementId: 'G-3BLEW90L4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_mqqI3NnOXHlPthRwr4NubE_bEcN4zw',
    appId: '1:653860201928:android:28b2b78e1313a6ff3f0cfd',
    messagingSenderId: '653860201928',
    projectId: 'pmg-engineering-pvt-ltd',
    storageBucket: 'pmg-engineering-pvt-ltd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5DTheem7RteGrH70wxB4uVL2pHWEafDg',
    appId: '1:653860201928:ios:72be657dc2f7d14c3f0cfd',
    messagingSenderId: '653860201928',
    projectId: 'pmg-engineering-pvt-ltd',
    storageBucket: 'pmg-engineering-pvt-ltd.firebasestorage.app',
    iosBundleId: 'com.chandu.pmgAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5DTheem7RteGrH70wxB4uVL2pHWEafDg',
    appId: '1:653860201928:ios:72be657dc2f7d14c3f0cfd',
    messagingSenderId: '653860201928',
    projectId: 'pmg-engineering-pvt-ltd',
    storageBucket: 'pmg-engineering-pvt-ltd.firebasestorage.app',
    iosBundleId: 'com.chandu.pmgAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-4fT4NOV6tfsVgirRxu2vD1ywAyAU9A',
    appId: '1:653860201928:web:6f555613c544ebe93f0cfd',
    messagingSenderId: '653860201928',
    projectId: 'pmg-engineering-pvt-ltd',
    authDomain: 'pmg-engineering-pvt-ltd.firebaseapp.com',
    storageBucket: 'pmg-engineering-pvt-ltd.firebasestorage.app',
    measurementId: 'G-9CMX5MF3ZW',
  );
}
